accr/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import password_reset, password_reset_done
from django.views.generic import RedirectView
from registration.backends.hmac.views import RegistrationView

from accr import settings
from main.forms import RegistrationFormTOSAndEmail
from registration.forms import RegistrationFormUniqueEmail

urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  url(r'^', include('main.urls', namespace='main')),

                  url(r'^accounts/register/$', RegistrationView.as_view(form_class=RegistrationFormTOSAndEmail),
                      name='registration_register'),
                  url(r'^accounts/', include('registration.backends.hmac.urls')),

                  url(r'^accounts/profile/$', RedirectView.as_view(url='/account/', permanent=False),
                      name='ProfilePage'),
                  # url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/successfully_logged_out/'}),
                  url(r'account/', include('account.urls', namespace='account')),

                  # url(r'^accounts/password/reset/done/$', 'django.contrib.auth.views.password_reset_done'),
                  # url(r'^accounts/password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
                  #     'django.contrib.auth.views.password_reset_confirm', {'post_reset_redirect': '/user/password/done/'}),
                  # url(r'^accounts/password/done/$', 'django.contrib.auth.views.password_reset_complete'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf import settings
from django.conf.urls import include, url

# from .views import (
#     news_list
# )
from registration.views import RegistrationView

# from main.forms import UserForm
from main.views import resend_activation_email
from .views import (
    MainPageView,
    AccessCardView, NewDesign)

urlpatterns = [
    url(r'^$', MainPageView.as_view(), name='main_page'),
    url(r'^card/$', AccessCardView.as_view(), name='access_card'),
    url(r'^new/$', NewDesign.as_view(), name='new_design'),
    url(r'^accounts/reactivate/$', resend_activation_email, name='account_reactivate'),
]

main/forms.py
from django import forms
from registration import validators
from registration.forms import RegistrationFormUniqueEmail, RegistrationForm

from account.models import Reporter


class RegistrationFormTermsOfServiceRu(RegistrationForm):
    """
    Subclass of ``RegistrationForm`` which adds a required checkbox
    for agreeing to a site's Terms of Service.

    """
    tos = forms.BooleanField(
        widget=forms.CheckboxInput,
        label=(
            'Даю свое согласие на обработку моих персональных данных, предусмотренноеЗаконом Российской Федерации от 27 июля 2006 года № 152-ФЗ «О персональных данных».'),
        error_messages={
            'required': validators.TOS_REQUIRED,
        }
    )


class RegistrationFormTOSAndEmail(RegistrationFormUniqueEmail, RegistrationFormTermsOfServiceRu):
    pass


class ReporterForm(forms.Form):
    reporter = forms.ModelMultipleChoiceField(queryset=Reporter.objects.all())


class ResendActivationEmailForm(forms.Form):
    email = forms.EmailField(required=True)

main/views.py
from random import randint

from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.template import Context
from django.views.generic import FormView
from django.views.generic import TemplateView

from django.views.generic.base import ContextMixin
from django.views.generic.detail import SingleObjectMixin
from registration.forms import User
from reportlab.graphics.barcode import code93
from reportlab.lib.units import cm, mm
from reportlab.lib.utils import ImageReader
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase import ttfonts
from reportlab.pdfgen import canvas

from account.models import MassMedia, Reporter
from accr import settings
from accr.settings import ACCESS_COVER
from main.forms import ReporterForm

from .forms import ResendActivationEmailForm
from django.core import signing
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string


class MainPageView(TemplateView):
    template_name = 'main_page.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return HttpResponseRedirect('/account/')
        else:
            return super(MainPageView, self).dispatch(request)


class AccessCardView(SingleObjectMixin, FormView, ContextMixin):
    """ Application for accreditation, pdf document """
    # Create the HttpResponse object with the appropriate PDF headers.
    response = HttpResponse(content_type='application/pdf')
    # response['Content-Disposition'] = 'attachment; filename="application.pdf"'

    response['Content-Disposition'] = 'filename="application.pdf"'
    success_url = '/card/'
    template_name = 'access_card_report.html'
    form_class = ReporterForm

    def report(self, reporters):
        # Create the PDF object, using the response object as its "file."
        pdf = canvas.Canvas(self.response)

        times_bold = ttfonts.TTFont('TimesBold', 'Times New Roman Cyr Bold.ttf')
        times = ttfonts.TTFont('Times', 'Times New Roman Cyr.ttf')
        pdfmetrics.registerFont(times_bold)
        pdfmetrics.registerFont(times)
        saved = False
        access_cover = ImageReader(ACCESS_COVER)
        times_bold = ttfonts.TTFont('TimesBold', 'Times New Roman Cyr Bold.ttf')
        times = ttfonts.TTFont('Times', 'Times New Roman Cyr.ttf')
        pdfmetrics.registerFont(times_bold)
        pdfmetrics.registerFont(times)

        count = 1

        margin = self.margins()

        for reporter in reporters:
            if count % 6 == 0:
                pdf.showPage()
                margin = self.margins()
                saved = True
            else:
                saved = False
            pdf.drawImage(access_cover, 3 * cm, margin['main_cover'] * cm, 13.75 * cm, 4.5 * cm)
            try:
                reporter_face = ImageReader(reporter.image_crop)
            except:
                reporter_face = ImageReader('main/static/main/img/unknown.jpg')
            pdf.drawImage(reporter_face, 3.2 * cm, margin['face'] * cm, 2.83 * cm, 3.7 * cm)
            watermark = ImageReader('access_watermark.png')
            pdf.drawImage(watermark, 3.02 * cm, margin['watermark'] * cm, 4.3 * cm, 4.45 * cm, mask='auto')

            pdf.setFont("TimesBold", 13)

            if len(reporter.surname) > 13:
                pdf.setFont("TimesBold", 11)
            pdf.drawString(6.3 * cm, margin['surname'] * cm, reporter.surname)
            pdf.drawString(6.3 * cm, margin['name'] * cm, reporter.name)
            pdf.drawString(6.3 * cm, margin['lastname'] * cm, reporter.lastname)

            pdf.setFont("TimesBold", 11)
            pdf.setFillColorRGB(255, 0, 0)
            if len(reporter.post) < 16:
                pdf.drawString(6.3 * cm, margin['post'] * cm, reporter.post)
            else:
                pdf.drawString(6.3 * cm, margin['post'] * cm, reporter.post[0:16])
                pdf.drawString(6.3 * cm, (margin['post'] - 0.42) * cm, reporter.post[16:32])

            pdf.setFillColorRGB(0, 0, 161)
            if len(reporter.massmedia.__str__()) < 16:
                pdf.drawString(6.3 * cm, margin['massmedia'] * cm, reporter.massmedia.__str__())
            else:
                pdf.drawString(6.3 * cm, margin['massmedia'] * cm, reporter.massmedia.__str__()[0:17])
                pdf.drawString(6.3 * cm, (margin['massmedia'] - 0.42) * cm, reporter.massmedia.__str__()[16:32])

            unique_num = randint(100001, 999999)
            unique_str = "PR-%s-%s" % (16, unique_num)

            pdf.setFont("TimesBold", 9)
            pdf.setFillColorRGB(255, 0, 0)
            pdf.drawString(3.6 * cm, margin['u_str_left'] * cm, unique_str)
            pdf.setFillColorRGB(0, 0, 161)
            pdf.drawString(14.35 * cm, margin['u_str_right'] * cm, unique_str)

            # qrw = QrCodeWidget('Helo World!')
            # qrw.draw()

            barcode = code93.Standard93(str(unique_num), barWidth=0.25 * mm, barHeight=15 * mm)

            # drawOn puts the barcode on the canvas at the specified coordinates

            pdf.setFillColorRGB(0, 0, 0)
            barcode.drawOn(pdf, 9.5 * cm, margin['barcode'] * cm)
            pdf.drawString(10.8 * cm, margin['barcode_num'] * cm, str(unique_num))

            for key, value in margin.items():
                margin[key] = value - 5

            reporter.printed = True
            reporter.save()
            count += 1

        if not saved:
            pdf.showPage()
        pdf.save()
        return self.response

    def get_context_data(self, **kwargs):
        massmedias = MassMedia.objects.all()
        reporters = []
        for mm in massmedias:
            for rep in mm.reporter_set.all():
                if rep.image_crop:
                    reporters.append(rep)
        reporters.sort(key=lambda rep: rep.updated, reverse=True)
        context = dict()
        context['reporters'] = reporters
        return context

    def post(self, request, *args, **kwargs):
        # print(self.request.POST)
        form = self.get_form()
        # print(form)
        if not form.is_valid():
            return HttpResponseRedirect('/card/')
        reporters = form.cleaned_data['reporter']

        # reporters = form.cleaned_data['reporter']
        # reporters = {}
        # for massmedia in massmedias:
        #     for reporter in massmedia.reporter_set.all():
        #         reporters[reporter.id] = reporter.__str__()
        # print(reporters)
        # for massmedia
        return self.report(reporters)

    def margins(self):
        margin = {
            'main_cover': 23.5,
            'face': 24.04,
            'surname': 27.4,
            'name': 26.8,
            'lastname': 26.2,
            'post': 25.5,
            'massmedia': 24.5,
            'u_str_left': 23.65,
            'u_str_right': 26.15,
            'barcode': 23.9,
            'barcode_num': 23.6,
            'watermark': 23.53,
        }
        return margin


class NewDesign(TemplateView):
    template_name = 'base_old.html'



# todo make CBV
def resend_activation_email(request):
    email_body_template = 'registration/activation_email.txt'
    email_subject_template = 'registration/activation_email_subject.txt'

    if not request.user.is_anonymous():
        return HttpResponseRedirect('/')

    context = Context()

    form = None
    if request.method == 'POST':
        form = ResendActivationEmailForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data["email"]
            users = User.objects.filter(email=email, is_active=0)

            if not users.count():
                form._errors["email"] = 'Учетная запись на таком e-mail не найдена или уже зарегистрирована.'

            REGISTRATION_SALT = getattr(settings, 'REGISTRATION_SALT', 'registration')
            print(REGISTRATION_SALT)
            for user in users:
                activation_key = signing.dumps(
                    obj=getattr(user, user.USERNAME_FIELD),
                    salt=REGISTRATION_SALT,
                )
                context = {}
                context['activation_key'] = activation_key
                context['expiration_days'] = settings.ACCOUNT_ACTIVATION_DAYS
                context['site'] = get_current_site(request)

                subject = render_to_string(email_subject_template,
                                           context)
                # Force subject to a single line to avoid header-injection
                # issues.
                subject = ''.join(subject.splitlines())
                message = render_to_string(email_body_template,
                                           context)
                user.email_user(subject, message, settings.DEFAULT_FROM_EMAIL)
                context['email'] = form.cleaned_data["email"]
                return render(request, 'registration/resend_activation_email_done.html', context)

    if not form:
        form = ResendActivationEmailForm()

    context.update({"form": form})
    return render(request, 'registration/resend_activation_email_form.html', context)

main/templates/access_card_report.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Генерация обложек для пропусков{% endblock %}

{% block breadcrumbs %}
    <!-- BREADCRUMBS -->
    <div class="row no-margin-bot no-padding-left no-padding-right accr-breadcrumb">
        <nav>
            <div class="nav-wrapper">
                <div class="col s12 accr-gray">
                    <a href="/" class="breadcrumb">Главная</a>
                    <a href="" class="breadcrumb">Генерация обложек для пропусков</a>
                </div>
            </div>
        </nav>
    </div>
{% endblock %}

{% block content %}


    <!-- PAGE CONTENT -->
    <form action="" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col s12">
                <table class=" bordered highlight" id="sortable">
                    <thead>
                    <tr>
                        <th data-field="id">№</th>
                        <th data-field="id" class="center-align">ФИО<i class="large material-icons"
                                                                       style="font-size: 1rem">swap_vert</i>
                        </th>
                        <th data-field="id" class="center-align">Морда лица</th>
                        <th data-field="name" class="center-align">СМИ<i class="large material-icons"
                                                                         style="font-size: 1rem">swap_vert</i>
                        </th>
                        <th data-field="price" class="center-align">Дата создания<i class="large material-icons"
                                                                                    style="font-size: 1rem">swap_vert</i>
                        </th>
                        <th data-field="price" class="center-align">Дата обновления<i
                                class="large material-icons" style="font-size: 1rem">swap_vert</i></th>
                        <th data-field="price" class="center-align">Обложка сформирована?<i
                                class="large material-icons" style="font-size: 1rem">swap_vert</i></th>
                        <th data-field="price" class="center-align">Печатать?</th>
                        <th></th>
                    </tr>
                    </thead>

                    <tbody>

                    {% for reporter in reporters %}
                        <tr>
                            <td>{{ forloop.counter }} </td>
                            <td>{{ reporter }}</td>

                            <td>
                                {% if reporter.image_crop %}
                                    <img src="{{ reporter.image_crop.url }}" alt="{{ reporter }}"
                                         class="materialboxed"
                                         width="35px" data-caption="{{ reporter }}">
                                {% else %}
                                    <img src="{% static 'main/img/unknown.jpg' %}" class="materialboxed" width="35px">
                                {% endif %}
                            </td>

                            <td>{{ reporter.massmedia }}</td>
                            <td>{{ reporter.added }}</td>
                            <td>{{ reporter.updated }}</td>
                            <td class="center-align">
                                {% if reporter.printed %}
                                    <span class="green-text">Да</span>
                                {% else %}
                                    <span class="red-text">Нет</span>
                                {% endif %}
                            </td>
                            <td class="center-align">
                                <input type="checkbox" id="id_{{ reporter.id }}" name="reporter"
                                       value="{{ reporter.id }}"
                                       {% if not reporter.printed %}checked{% endif %}/>
                                <label for="id_{{ reporter.id }}"></label>
                            </td>
                            <td></td>

                        </tr>
                    {% endfor %}

                    <tr>
                        <td colspan="7" class="center-align">
                            <button class="btn waves-effect waves-light coral" type="submit" name="action">
                                Напечатать обложки
                                <i class="material-icons right">send</i>
                            </button>
                        </td>
                        <td class="center-align">
                            <input type="checkbox" id="id_toggle" onClick="toggle(this)"/>
                            <label for="id_toggle"></label>
                        </td>
                    </tr>

                    </tbody>
                </table>

            </div>
        </div>
        {#        <div class="row">#}
        {#            <div class="col s8 offset-s2 center-align">#}
        {#                <button class="btn waves-effect waves-light coral" type="submit" name="action">#}
        {#                    Напечатать обложки#}
        {#                    <i class="material-icons right">send</i>#}
        {#                </button>#}
        {#            </div>#}
        {#            <div class="col s1 offset-s1 center-align">#}
        {#                <input type="checkbox" id="id_toggle" onClick="toggle(this)"/>#}
        {#                <label for="id_toggle"></label>#}
        {#            </div>#}
        {#        </div>#}
    </form>

{% endblock %}

{% block js %}
    <script>
        $(document).ready(function () {
                    $("#sortable").tablesorter({
                        headers: {0: {sorter: false}}
                    });
                }
        );
    </script>
    <script>
        function toggle(source) {
            checkboxes = document.getElementsByName('reporter');
            for (var i = 0, n = checkboxes.length; i < n; i++) {
                checkboxes[i].checked = source.checked;
            }
        }
    </script>
{% endblock %}

main/templates/base.html
{% load staticfiles %}
{% load extras %}

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title>
        {% block title %}Starter Template - Materialize{% endblock title %}
    </title>

    <!-- CSS  -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="{% static 'main/css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="{% static 'main/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'main/img/favicon.ico' %}">
    {#    <script type="text/javascript" src="{% static 'main/js/sorttable.js' %}"></script>#}
    <script src="{% static 'main/js/jquery-2.1.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'main/js/jquery.tablesorter.js' %}"></script>
    {% block css %}{% endblock %}
</head>

<body>
<header>
    <nav class="accr-nav dark-blue">
        <div class="nav-wrapper container">
            <a href="/" class="brand-logo accr-logo"></a>
            <div class="accr-logo-1">
                <span class="accr-logo-2 hide-on-med-and-down">АККРЕДИТАЦИЯ</span><br>
                <span class="accr-logo-3 hide-on-med-and-down">СРЕДСТВ МАССОВОЙ ИНФОРМАЦИИ</span>
                <span class="accr-logo-4 hide-on-med-and-down">
                {% if user.is_authenticated %}
                    <ul id="nav-mobile" class="right hide-on-med-and-down">
                    {% if request.user|has_group:"employee" or request.user.is_superuser %}
                        <li><a href="{% url 'main:access_card' %}">Генерация обложек</a></li>
                    {% endif %}
                        <li><a href="{% url 'auth_logout' %}?next=/"> Выйти из системы</a></li>
                    </ul>
                {% else %}
                    ДОБРО ПОЖАЛОВАТЬ!
                {% endif %}
            </span>
                <ul class="side-nav" id="mobile-demo">
                    {% if request.user|has_group:"employee" or request.user.is_superuser %}
                        <li><a href="{% url 'main:access_card' %}">Генерация обложек</a></li>
                    {% endif %}
                    <li><a href="{% url 'auth_logout' %}?next=/"> Выйти из системы</a></li>
                </ul>
            </div>
            <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>

        </div>
    </nav>
</header>

<main class="container">
    {% block breadcrumbs %}
    {% endblock %}
    <div class="main-content">
        {% block content %}
        {% endblock %}
    </div>
</main>

<footer class="page-footer coral no-margin-top container">
    <div class="row">
        <div class="col s12">
            <span class="white-text">&copy; 2016 Правительство Калининградской области</span>
        </div>
    </div>
</footer>


<!--  Scripts-->

<script src="{% static 'main/js/materialize.js' %}"></script>
<script src="{% static 'main/js/init.js' %}"></script>


{% block js %}
{% endblock %}
<!-- Design by Anastasiya Turulina -->
<!-- Makeup and web-develop by Oleg Artemov -->
</body>
</html>

main/templates/base_old.html
{% load staticfiles %}
{% load extras %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title>
        {% block title %}Starter Template - Materialize{% endblock title %}
    </title>

    <!-- CSS  -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="{% static 'main/css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="{% static 'main/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
    {#    <script type="text/javascript" src="{% static 'main/js/sorttable.js' %}"></script>#}
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="{% static 'main/js/jquery.tablesorter.js' %}"></script>
    {% block css %}{% endblock %}
</head>
<body>
<header>
    <nav class="indigo darken-1" role="navigation">
        <div class="nav-wrapper container"><a id="logo-container" href="/" class="brand-logo">Logo</a>
            <ul class="right hide-on-med-and-down">
                {#                <li><a href="{% url 'registration_register' %}">Авторизация</a></li>#}
                {% if request.user|has_group:"employee" or request.user.is_superuser %}
                    <li><a href="{% url 'main:access_card' %}">Генерация обложек</a></li>
                {% endif %}
                {% if user.is_authenticated %}
                    <li><a href="{% url 'auth_logout' %}">Выйти из системы</a></li>
                {% else %}
                    <li><a href="{% url 'auth_login' %}">Вход в систему</a></li>
                {% endif %}

            </ul>

            <ul id="nav-mobile" class="side-nav">
                {% if request.user|has_group:"employee" or request.user.is_superuser %}
                    <li><a href="{% url 'main:access_card' %}">Генерация обложек</a></li>
                {% endif %}
                {% if user.is_authenticated %}
                    <li><a href="{% url 'auth_logout' %}">Выйти из системы</a></li>
                {% else %}
                    <li><a href="{% url 'auth_login' %}">Вход в систему</a></li>
                {% endif %}
            </ul>
            <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
        </div>
    </nav>
</header>

<main>
    {% block content %}{% endblock content %}
</main>

<footer class="page-footer orange">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">Company Bio</h5>
                <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's
                    our full time job. Any amount would help support and continue development on this project and is
                    greatly appreciated.</p>


            </div>
            <div class="col l3 s12">
                <h5 class="white-text">Settings</h5>
                <ul>
                    <li><a class="white-text" href="#!">Link 1</a></li>
                    <li><a class="white-text" href="#!">Link 2</a></li>
                    <li><a class="white-text" href="#!">Link 3</a></li>
                    <li><a class="white-text" href="#!">Link 4</a></li>
                </ul>
            </div>
            <div class="col l3 s12">
                <h5 class="white-text">Connect</h5>
                <ul>
                    <li><a class="white-text" href="#!">Link 1</a></li>
                    <li><a class="white-text" href="#!">Link 2</a></li>
                    <li><a class="white-text" href="#!">Link 3</a></li>
                    <li><a class="white-text" href="#!">Link 4</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            Made by <a class="orange-text text-lighten-3" href="http://materializecss.com">Materialize</a>
        </div>
    </div>
</footer>


<!--  Scripts-->

<script src="{% static 'main/js/materialize.js' %}"></script>
<script src="{% static 'main/js/init.js' %}"></script>


{% block js %}
{% endblock %}

</body>
</html>

main/templates/main_page.html
{% extends 'base.html' %}

{% block title %}
    Главная - Аккредитация журналистов при Правительстве Калининградской области
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col m12 l6">
            <p>Аккредитация проводится в период с 10.12.2018 г. по 19.12.2018 г., в соответствии с Правилами
                аккредитации журналистов средств массовой информации при правительстве Калининградской области,
                утвержденными постановлением от 02 августа 2010 года № 595.</p>
            <p>Согласно постановления, аккредитационные удостоверения выдаются СМИ в пределах следующих квот:</p>
            <p>1) периодические печатные издания – не более 3 человек;</p>
            <p>2) телевизионные СМИ – не более 3 съемочных групп в составе корреспондента и оператора;</p>
            <p>3) радиокомпании – не более 2 человек;</p>
            <p>4) интернет-СМИ – не более 4 человек.</p>
        </div>
        <div class="col m12 l6">
            <form method="post" action="{% url 'auth_login' %}" class="col s12">
                {% csrf_token %}
                <div class="row">
                    <div class="input-field col m12 offset-l3 l9">
                        <input autofocus="" id="id_username" maxlength="254" name="username" type="text" required="">
                        <label for="id_username" class="">Имя пользователя</label>

                    </div>
                </div>

                <div class="row">
                    <div class="input-field col m12 offset-l3 l9">
                        <label for="id_password">Пароль</label>
                        <input id="id_password" name="password" type="password" required="">


                    </div>
                </div>
                <div class="row">
                    <div class="col m6 l6 offset-l3">
                        <button class="btn waves-effect waves-light coral" type="submit"
                                name="action" style="float: left">
                            Вход
                            <i class="material-icons right">send</i>
                        </button>
                    </div>
                    <div class="col m6 l3 register-large">
                            <a href="{% url 'registration_register' %}" class="btn waves-effect waves-light blue-grey lighten-3" style="float: right">
                                Регистрация
                            </a>
                    </div>
                </div>
                <div class="row">
                    <div class="col m6 l6 offset-l3 register-small">
                        <button class="btn waves-effect waves-light blue-grey lighten-3" type="submit"
                                name="action">
                            Регистрация
                        </button>
                    </div>
                </div>
                <div class="row">
                    <div class="col m6 l6 offset-l3">
                        <a href="{% url 'auth_password_reset' %}">Забыли пароль?</a>
                    </div>
                </div>
                <input type="hidden" name="next" value="">
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            <h3 class="coral-text">Порядок проведения<br>аккредитации:</h3>
            <p align="justify">Для прохождения аккредитации журналистов необходимо зарегистрироваться как СМИ и
                заполнить регистрационные данные.</p>
            <p align="justify">Порядок прохождения аккредитации:</p>
            <p align="justify">- регистрируется РЕДАКТОР СМИ (или сотрудник, уполномоченный это сделать от лица
                редакции);</p>
            <p align="justify">- заполняет сведения о СМИ, аккредитуемых сотрудниках (в электронном виде);</p>
            <p align="justify">- получает сгенерированные формы документов, подписывает их в редакции.</p>
            <p align="justify">На основании сведений, заполненных в системе, генерируются учетная карточка СМИ и учетные
                карточки сотрудников. Эти учетные карточки необходимо распечатать, подписать в
                редакции и предоставить с копиями учредительных документов в обмен на аккредитационные удостоверения 2018 года (при
                получении)</p>
            <p align="justify">Для, сотрудников, имеющих аккредитационные удостоверения 2017 года, карточки необходимо
                будет сдать Урженко Марии (каб. 339, тел 599-994) в срок до 25.12.2017 г.</p>
            <p align="justify"><strong>Внимание!!! Подать все сведения в электронном виде необходимо до 18:00 09.12.2017
                года.</strong></p>
            <p align="justify">Выдача аккредитационных удостоверений будет производиться 22.12.2017 - 29.12.2017 с
                предварительным информированием о готовности удостоверений по электронной почте.</p>
            <p align="justify">Аккредитационные удостоверения 2017 года будут действовать до 23:00 31.12.2017 г.</p>
            <p>Справки по процессу аккредитации: +7 4012 599-971 – Артемов Олег Викторович, e-mail: <a href="mailto:o.artemov@gov39.ru">o.artemov@gov39.ru</a></p>
            <p>Старая версия сайта: <a href="http://accr2.gov39.ru">http://accr2.gov39.ru</a></p>

        </div>
    </div>
{% endblock content %}